spring:
  application:
    name: first-service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 9100
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    UserClient#getUser():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

